FROM node:14.1-alpine AS builder

WORKDIR /opt/web
COPY package.json package-lock.json ./

RUN npm cache verify
RUN npm install

ENV PATH="./node_modules/.bin:$PATH"

COPY . ./
RUN ng build --prod

FROM nginx:1.17-alpine
COPY --from=builder /opt/web/dist/techshow-website /usr/share/nginx/html